# Generated by Django 5.2.5 on 2025-08-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'month')},
        ),
    ]
